/* ------------------------------------------------------------------ */
/*  Jack Bank — per-user settings schema (100+ parameters)            */
/*  The admin edits these per user; they are stored as JSONB via      */
/*  jb_user_settings. Defaults merge client-side.                     */
/* ------------------------------------------------------------------ */

export type CfgField = {
  key: string
  label: string
  type: 'bool' | 'num' | 'select' | 'text'
  options?: string[]
  min?: number
  max?: number
  step?: number
  rupee?: boolean
  hint?: string
}

export type CfgGroup = { title: string; fields: CfgField[] }

export const USER_SETTINGS_SCHEMA: CfgGroup[] = [
  {
    title: 'Transfers & UPI',
    fields: [
      { key: 'transfers_enabled', label: 'Transfers allowed', type: 'bool' },
      { key: 'upi_enabled', label: 'UPI payments', type: 'bool' },
      { key: 'scan_pay_enabled', label: 'Scan & pay', type: 'bool' },
      { key: 'request_enabled', label: 'Money requests', type: 'bool' },
      { key: 'upi_lite_enabled', label: 'UPI Lite (offline)', type: 'bool' },
      { key: 'upi_autopay_enabled', label: 'UPI AutoPay mandates', type: 'bool' },
      { key: 'pin_required', label: 'PIN for every transfer', type: 'bool' },
      { key: 'per_txn_limit', label: 'Per-transaction limit', type: 'num', rupee: true },
      { key: 'daily_txn_limit', label: 'Daily transfer limit', type: 'num', rupee: true },
      { key: 'weekly_txn_limit', label: 'Weekly transfer limit', type: 'num', rupee: true },
      { key: 'monthly_txn_limit', label: 'Monthly transfer limit', type: 'num', rupee: true },
      { key: 'upi_daily_limit', label: 'UPI daily limit', type: 'num', rupee: true },
      { key: 'min_txn_amount', label: 'Minimum transfer amount', type: 'num', rupee: true },
      { key: 'max_txn_amount', label: 'Maximum transfer amount', type: 'num', rupee: true },
    ],
  },
  {
    title: 'Deposits & Withdrawals',
    fields: [
      { key: 'deposit_enabled', label: 'Deposits allowed', type: 'bool' },
      { key: 'withdraw_enabled', label: 'Withdrawals allowed', type: 'bool' },
      { key: 'auto_approve_deposit', label: 'Auto-approve deposits', type: 'bool' },
      { key: 'auto_approve_withdrawal', label: 'Auto-approve withdrawals', type: 'bool' },
      { key: 'max_single_withdrawal', label: 'Max single withdrawal', type: 'num', rupee: true },
      { key: 'daily_withdraw_limit', label: 'Daily withdrawal limit', type: 'num', rupee: true },
      { key: 'min_balance', label: 'Minimum balance', type: 'num', rupee: true },
      { key: 'max_balance', label: 'Maximum balance cap', type: 'num', rupee: true },
    ],
  },
  {
    title: 'Cards',
    fields: [
      { key: 'cards_enabled', label: 'Cards enabled', type: 'bool' },
      { key: 'debit_card_enabled', label: 'Debit card', type: 'bool' },
      { key: 'credit_card_enabled', label: 'Credit card', type: 'bool' },
      { key: 'freeze_debit', label: 'Freeze debit card', type: 'bool' },
      { key: 'freeze_credit', label: 'Freeze credit card', type: 'bool' },
      { key: 'card_daily_limit', label: 'Card daily spend limit', type: 'num', rupee: true },
      { key: 'card_txn_limit', label: 'Card per-txn limit', type: 'num', rupee: true },
      { key: 'contactless_enabled', label: 'Contactless (tap & pay)', type: 'bool' },
      { key: 'contactless_limit', label: 'Contactless limit', type: 'num', rupee: true },
      { key: 'atm_enabled', label: 'ATM withdrawals', type: 'bool' },
      { key: 'atm_daily_limit', label: 'ATM daily limit', type: 'num', rupee: true },
      { key: 'card_network', label: 'Card network', type: 'select', options: ['RuPay', 'Visa', 'Mastercard'] },
      { key: 'card_design', label: 'Card design', type: 'select', options: ['AMOLED Gold', 'Midnight Black', 'Neon Purple', 'Classic Silver'] },
    ],
  },
  {
    title: 'Loans & Credit',
    fields: [
      { key: 'loans_enabled', label: 'Loans allowed', type: 'bool' },
      { key: 'auto_approve_loan', label: 'Auto-approve loans', type: 'bool' },
      { key: 'loan_limit', label: 'Loan limit', type: 'num', rupee: true },
      { key: 'loan_tenure_cap', label: 'Max loan tenure (months)', type: 'num', min: 1, max: 60 },
      { key: 'loan_rate_override', label: 'Loan interest rate (%)', type: 'num', min: 0, max: 48, step: 0.1, hint: 'Overrides bank default rate' },
      { key: 'min_loan_amount', label: 'Minimum loan amount', type: 'num', rupee: true },
      { key: 'credit_score_boost', label: 'Credit score boost', type: 'num', min: -200, max: 200, hint: 'Added to computed score' },
      { key: 'overdraft_enabled', label: 'Overdraft facility', type: 'bool' },
      { key: 'overdraft_limit', label: 'Overdraft limit', type: 'num', rupee: true },
      { key: 'emi_day', label: 'EMI due day', type: 'num', min: 1, max: 28 },
    ],
  },
  {
    title: 'Investments (FD · MF · Stocks · Crypto)',
    fields: [
      { key: 'fd_enabled', label: 'Fixed deposits', type: 'bool' },
      { key: 'fd_rate_override', label: 'FD interest rate (%)', type: 'num', min: 0, max: 15, step: 0.1 },
      { key: 'fd_max_tenure', label: 'Max FD tenure (months)', type: 'num', min: 3, max: 120 },
      { key: 'min_fd_amount', label: 'Minimum FD amount', type: 'num', rupee: true },
      { key: 'mf_enabled', label: 'Mutual funds', type: 'bool' },
      { key: 'mf_daily_limit', label: 'MF daily investment limit', type: 'num', rupee: true },
      { key: 'min_mf_amount', label: 'Minimum MF investment', type: 'num', rupee: true },
      { key: 'max_sip_amount', label: 'Maximum SIP amount', type: 'num', rupee: true },
      { key: 'stocks_enabled', label: 'Stock trading', type: 'bool' },
      { key: 'stock_daily_limit', label: 'Stock daily order value', type: 'num', rupee: true },
      { key: 'min_stock_order', label: 'Minimum order value', type: 'num', rupee: true },
      { key: 'crypto_enabled', label: 'Crypto trading', type: 'bool' },
    ],
  },
  {
    title: 'Fees, Rewards & Interest',
    fields: [
      { key: 'fee_exempt', label: 'Transfer fee exemption', type: 'bool' },
      { key: 'fee_pct_override', label: 'Transfer fee (%)', type: 'num', min: 0, max: 10, step: 0.1, hint: 'Overrides bank fee' },
      { key: 'cashback_enabled', label: 'Cashback', type: 'bool' },
      { key: 'cashback_pct_override', label: 'Cashback rate (%)', type: 'num', min: 0, max: 10, step: 0.1 },
      { key: 'reward_rate', label: 'Reward points per ₹100', type: 'num', min: 0, max: 20, step: 0.5 },
      { key: 'welcome_bonus', label: 'Welcome bonus', type: 'num', rupee: true },
      { key: 'savings_interest_rate', label: 'Savings interest (%) p.a.', type: 'num', min: 0, max: 12, step: 0.1 },
      { key: 'priority_service', label: 'Priority service', type: 'bool' },
      { key: 'foreign_txn_fee', label: 'Cross-bank fee (%)', type: 'num', min: 0, max: 10, step: 0.1 },
    ],
  },
  {
    title: 'Security',
    fields: [
      { key: 'allow_login', label: 'Login allowed', type: 'bool' },
      { key: 'two_factor_enabled', label: 'Two-factor auth (2FA)', type: 'bool' },
      { key: 'biometric_enabled', label: 'Biometric login', type: 'bool' },
      { key: 'pin_attempts_max', label: 'Max PIN attempts', type: 'num', min: 3, max: 10 },
      { key: 'session_timeout_min', label: 'Session timeout (min)', type: 'num', min: 1, max: 240 },
      { key: 'device_limit', label: 'Device limit', type: 'num', min: 1, max: 10 },
      { key: 'security_alerts', label: 'Security alerts', type: 'bool' },
      { key: 'block_on_suspicious', label: 'Auto-block on suspicious activity', type: 'bool' },
      { key: 'login_alerts', label: 'Login alerts', type: 'bool' },
      { key: 'transaction_alerts', label: 'Transaction alerts', type: 'bool' },
    ],
  },
  {
    title: 'Notifications',
    fields: [
      { key: 'notifications_enabled', label: 'Notifications', type: 'bool' },
      { key: 'email_notifications', label: 'Email notifications', type: 'bool' },
      { key: 'push_notifications', label: 'Push notifications', type: 'bool' },
      { key: 'sms_notifications', label: 'SMS notifications', type: 'bool' },
      { key: 'txn_notifications', label: 'Transaction alerts', type: 'bool' },
      { key: 'security_notifications', label: 'Security alerts', type: 'bool' },
      { key: 'marketing_notifications', label: 'Offers & marketing', type: 'bool' },
      { key: 'statement_frequency', label: 'Statement frequency', type: 'select', options: ['daily', 'weekly', 'monthly'] },
      { key: 'statement_email', label: 'Email statements', type: 'bool' },
    ],
  },
  {
    title: 'Account & Preferences',
    fields: [
      { key: 'account_tier', label: 'Account tier', type: 'select', options: ['Basic', 'Silver', 'Gold', 'Platinum'] },
      { key: 'risk_profile', label: 'Risk profile', type: 'select', options: ['Low', 'Moderate', 'High'] },
      { key: 'language', label: 'Language', type: 'select', options: ['English', 'Hindi'] },
      { key: 'theme', label: 'Theme', type: 'select', options: ['AMOLED', 'Dark', 'Light'] },
      { key: 'lock_theme', label: 'Lock theme (user cannot change)', type: 'bool' },
      { key: 'show_balance', label: 'Show balance on home', type: 'bool' },
      { key: 'kyc_auto_approve', label: 'Auto-approve KYC', type: 'bool' },
      { key: 'signup_bonus_enabled', label: 'Signup bonus', type: 'bool' },
      { key: 'referral_enabled', label: 'Referral rewards', type: 'bool' },
      { key: 'international_enabled', label: 'Cross-border (virtual)', type: 'bool' },
      { key: 'bill_pay_enabled', label: 'Bill payments', type: 'bool' },
      { key: 'wallet_enabled', label: 'Wallet top-up', type: 'bool' },
      { key: 'display_density', label: 'Display density', type: 'select', options: ['Comfortable', 'Compact'] },
      { key: 'monthly_report', label: 'Monthly report', type: 'bool' },
      { key: 'daily_statement', label: 'Daily digest', type: 'bool' },
      { key: 'status_note', label: 'Internal admin note', type: 'text' },
    ],
  },
]

export const DEFAULT_USER_CFG: Record<string, string | number | boolean> = {
  transfers_enabled: true,
  upi_enabled: true,
  scan_pay_enabled: true,
  request_enabled: true,
  upi_lite_enabled: false,
  upi_autopay_enabled: false,
  pin_required: true,
  per_txn_limit: 50000,
  daily_txn_limit: 200000,
  weekly_txn_limit: 500000,
  monthly_txn_limit: 1500000,
  upi_daily_limit: 100000,
  min_txn_amount: 1,
  max_txn_amount: 100000,

  deposit_enabled: true,
  withdraw_enabled: true,
  auto_approve_deposit: false,
  auto_approve_withdrawal: false,
  max_single_withdrawal: 50000,
  daily_withdraw_limit: 100000,
  min_balance: 0,
  max_balance: 100000000,

  cards_enabled: true,
  debit_card_enabled: true,
  credit_card_enabled: true,
  freeze_debit: false,
  freeze_credit: false,
  card_daily_limit: 100000,
  card_txn_limit: 50000,
  contactless_enabled: true,
  contactless_limit: 5000,
  atm_enabled: true,
  atm_daily_limit: 20000,
  card_network: 'RuPay',
  card_design: 'AMOLED Gold',

  loans_enabled: true,
  auto_approve_loan: false,
  loan_limit: 200000,
  loan_tenure_cap: 24,
  loan_rate_override: 0,
  min_loan_amount: 1000,
  credit_score_boost: 0,
  overdraft_enabled: false,
  overdraft_limit: 0,
  emi_day: 5,

  fd_enabled: true,
  fd_rate_override: 0,
  fd_max_tenure: 36,
  min_fd_amount: 1000,
  mf_enabled: true,
  mf_daily_limit: 500000,
  min_mf_amount: 100,
  max_sip_amount: 50000,
  stocks_enabled: true,
  stock_daily_limit: 1000000,
  min_stock_order: 100,
  crypto_enabled: true,

  fee_exempt: false,
  fee_pct_override: 0,
  cashback_enabled: true,
  cashback_pct_override: 0,
  reward_rate: 1,
  welcome_bonus: 500,
  savings_interest_rate: 3.5,
  priority_service: false,
  foreign_txn_fee: 1,

  allow_login: true,
  two_factor_enabled: false,
  biometric_enabled: false,
  pin_attempts_max: 5,
  session_timeout_min: 30,
  device_limit: 3,
  security_alerts: true,
  block_on_suspicious: true,
  login_alerts: true,
  transaction_alerts: true,

  notifications_enabled: true,
  email_notifications: true,
  push_notifications: true,
  sms_notifications: false,
  txn_notifications: true,
  security_notifications: true,
  marketing_notifications: false,
  statement_frequency: 'monthly',
  statement_email: true,

  account_tier: 'Basic',
  risk_profile: 'Moderate',
  language: 'English',
  theme: 'AMOLED',
  lock_theme: false,
  show_balance: true,
  kyc_auto_approve: false,
  signup_bonus_enabled: true,
  referral_enabled: true,
  international_enabled: false,
  bill_pay_enabled: true,
  wallet_enabled: true,
  display_density: 'Comfortable',
  monthly_report: true,
  daily_statement: false,
  status_note: '',
}

export const TOTAL_USER_PARAMS = USER_SETTINGS_SCHEMA.reduce((a, g) => a + g.fields.length, 0)
